# Generated by Django 4.1.2 on 2023-07-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('tipo', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('autor', models.CharField(max_length=70)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumnos.editorial')),
            ],
        ),
    ]
